### PR TITLE
Pull Request for fixing compilation errors in compilation test tool

### PR DESCRIPTION
**Pull request by mad-jrodriguez**
The issue was reported here: https://github.com/MEN-Mikro-Elektronik/13MD05-90/issues/252

### CODE REVIEW

**Review by dpfeuffer — APPROVED** [review]
just a quick review without further investigation ;-)

**Comment by mad-jrodriguez** [comment]
> just a quick review without further investigation ;-)

For fixing the issue related with the hrtimer in kernel versions lower than 4.16, I have substituted the hrtimer wit the tasklet_hrtimer that is the old way to use the timers as Helmut suggested.

https://lore.kernel.org/netdev/20190301224821.29843-4-bigeasy@linutronix.de/t/

Additionally, I have added a change to cancel the timer in the z77_close function to release the timer resources.

**Review by mad-jsanjuan — APPROVED** [review]
Changes look good to me. Could we ask https://github.com/duagon-hhedwig to confirm the changes made on `z77_close()` look ok?

**Comment by dpfeuffer** [comment]
> Changes look good to me. Could we ask https://github.com/duagon-hhedwig to confirm the changes made on `z77_close()` look ok?

Yes, good idea!

**Comment by duagon-hhedwig** [comment]
> > just a quick review without further investigation ;-)
> 
> For fixing the issue related with the hrtimer in kernel versions lower than 4.16, I have substituted the hrtimer wit the tasklet_hrtimer that is the old way to use the timers as Helmut suggested.
> 
> https://lore.kernel.org/netdev/20190301224821.29843-4-bigeasy@linutronix.de/t/
> 
> Additionally, I have added a change to cancel the timer in the z77_close function to release the timer resources.

You are right! The release of the timer resources in z77_close were missing. The changes look fine to me, too

**Pull request merged**
